name: Docker Image Export and Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only when a new tag is pushed (e.g., v1.0.0)

jobs:
  export-and-release:
    name: Export Docker Image and Upload Release
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      # Step 2: Pull the Docker image
      - name: Pull Docker Image
        run: |
          IMAGE_NAME="quay.io/11notes/sonarr:4.0.16"
          echo "Pulling Docker image: $IMAGE_NAME"
          docker pull "$IMAGE_NAME"
      # Step 3: Export the Docker image to a tar file
      - name: Export Docker Image to Tar
        run: |
          IMAGE_NAME="quay.io/11notes/sonarr:4.0.16"
          TAR_FILE="sonarr.tar"
          echo "Exporting Docker image to tar file: $TAR_FILE"
          docker export "$(docker create "$IMAGE_NAME")" > "$TAR_FILE"
      # Step 4: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      # Step 5: Upload Release Asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sonarr.tar
          asset_name: sonarr.tar
          asset_content_type: application/x-tar
